import type { Metadata } from "next";
import { Geist, Geist_Mono,  Noto_Serif_Bengali  } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["bengali"],
  variable: "--font-noto-serif-bengali",
});

const solaimanLipi = localFont({
  src: "../public/SolaimanLipi.ttf",
  variable: "--font-solaiman-lipi",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body 
      lang="bn"
      className={`${notoSerifBengali.variable} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
